name: PolitiScales
basepath: 

plugins:
  - jekyll-redirect-from

collections:
   fr_FR:
      permalink: fr_FR/:name/
      title: Français
      output: true

t:
   fr_FR:
      header_desc: PolitiScales est un test politique utilisant 8 axes idéologiques pour vous aider à vos situer politiquement, ou simplement partager votre profil avec vos amis.
      footer: PolitiScales est une initiative du Discord « La Commune », librement inspirée de <a href="https://8values.github.io/">8values</a>.
      
      constructivism: Constructivisme
      essentialism: Essentialisme
      justice_soft: Justice réhabilitative
      justice_hard: Justice punitive
      progressism: Progressisme
      conservatism: Conservatisme
      internationalism: Internationalisme
      nationalism: Nationalisme
      communism: Communisme
      capitalism: Capitalisme
      regulationism: Régulationnisme
      laissez_faire: Laissez-faire
      ecology: Écologie
      productivism: Productivisme
      revo: Révolution
      refo: Réformisme
      
      result_anarchism: Anarchisme
      result_pragmatism: Pragmatisme
      result_feminism: Féminisme radical
      result_complotism: Complotisme
      result_veganism: Véganisme
      result_monarchism: Monarchisme
      result_religion: Missionnaire
      
      index_welcome: Bienvenue dans PolitiScales, le test politique <i>online</i>. Vous allez être confronté à une série d'affirmations. Pour chacune d'elles, cliquez sur le bouton correspondant à votre opinion.
      index_context: Les questions supposent que vous êtes citoyen d’une nation avec un système politique multi-parti et une économie de marché.
      index_advice: Vous pouvez tout à fait ne pas répondre à une question. Mais si vous ne comprenez pas le sens d'une question, essayez d'inverser son sens pour mieux comprendre ce qu'elle implique.
      index_warning: Ce test cherche à representer le panel le plus large possible d'opinions et contient donc des phrases qui peuvent vous choquer, en particulier concernant le racisme et l'homophobie.
      index_title_instructions: Instructions
      index_btn_start: Commencer le test
         
      help_whois: Qui sommes-nous ?
      help_desc: PolitiScales est un test politique utilisant 8 axes idéologiques pour vous aider à vos situer politiquement, ou simplement partager votre profil avec vos amis. Ce site internet est une initiative du Discord « La Commune », librement inspirée de <a href="https://8values.github.io/">8values</a>.
      help_constructivism1: Pourquoi les gens sont-ils comme ils sont ? Cet axe permet de vous situer entre deux pôles antagonistes répondant à cette question.
      help_constructivism2: Les <b>constructivistes</b> estiment qu’un individu se construit à partir de son environnement (notamment social), que les caractères qui le composent sont acquis.
      help_constructivism3: À l’inverse, les <b>essentialistes</b> partent du principe qu’un individu est par nature tel qu’il est, et que les caractères qui le composent sont innés.
      help_justice1: Les partisans de la <b>justice réhabilitative</b> estiment que le rôle de la Justice est de remettre les condamnés dans le "droit chemin", en leur faisant comprendre pourquoi ils ne doivent pas faire ce pour quoi ils ont été condamnés, et en les accompagnant tout au long de ce processus.
      help_justice2: À l’inverse, les partisans de la <b>justice punitive</b> partent du principe que le rôle de la Justice est dissuasif, à la fois pour les condamnés (pour éviter la récidive) et pour le reste de la société (en faisant des condamnés des exemples à ne pas suivre).
      help_progressism1: Les <b>progressistes</b> cherchent à instaurer un progrès social, à améliorer la société, sans se soucier des traditions. Ils estiment souvent l’époque présente comme meilleure que celles passées, et qu’il est nécessaire de poursuivre dans cette lancée.
      help_progressism2: À l’inverse, les <b>conservateurs</b> cherchent à garder le statu quo, voire à rétablir certaines valeurs établies jugées disparues ou en perdition. Les traditions, parmi lesquelles l’héritage religieux, sont mises en avant comme source de sagesse.
      help_internationalism1: <b>L’internationalisme</b> est un ensemble d’idées hétéroclites ayant pour point commun de ne pas hiérarchiser les pays et leurs habitants entre eux, et à promouvoir autant que possible leur coopération. Poussé à son maximum, l’objectif final de l’internationalisme est l’abolition des frontières.
      help_internationalism2: À l’inverse, le <b>nationalisme</b> est un ensemble d’idées hétéroclites ayant pour point commun de privilégier le pays et les habitants dans lequel il s’applique par rapport aux autres, et à légitimer l’existence d’une nation par peuple.
      help_communism1: Le <b>communisme</b> est une doctrine politique très vaste. Dans ce test, une prépondérance pour le communisme signifie simplement que vous êtes partisans de la propriété publique des moyens de productions.
      help_communism2: Le <b>capitalisme</b> est lui aussi un concept très ambivalent. Dans ce test, une prépondérance pour le capitalisme signifie simplement que vous êtes partisans de la propriété privée des moyens de productions.
      help_regulationism1: Cet axe représente l'attitude que doit avoir un état dans une économie de marché où une part importante des moyens de production sont privés. Libéraux et keynésiens s’opposent ainsi sur la méthode à adopter sans toutefois remettre en question le capitalisme. Si vous êtes plutôt capitaliste, cet axe représente votre but en matière d’économie. Si vous êtes communiste, cet axe représente ce que vous pouvez attendre de moins mauvais du système actuel.
      help_regulationism2: Le <b>régulationnisme</b>, ou interventionnisme, est une idée selon laquelle l’activité économique doit être régulée dans l’intérêt de tous. Cela peut passer par la législation, la planification, les subventions, une imposition variable…
      help_regulationism3: À l’inverse, le <b>laissez-faire</b> est une idée selon laquelle l’activité économique ne doit pas être régulée, car elle répondrait d’elle-même à l’intérêt général. Cela peut passer par une faible législation, peu ou pas de subventions, une imposition fixe et souvent faible, voire la suppression complète du rôle de l’État en matière d’économie.
      help_ecology1: <b>L’écologie</b>, en politique, privilégie la protection de l’environnement, en limitant autant que possible l’impact des activités humaines sur la biodiversité, quitte à limiter au passage lesdites activités humaines en modifiant plus ou moins radicalement le mode de vie actuel.
      help_ecology2: Le <b>productivisme</b> privilégie les besoins humain, notamment en soutenant la hausse de la production ou l’utilisation de méthodes ayant un impact incertain sur l’environnement.
      help_revo1: Les <b>révolutionnaires</b> auront tendance à privilégier l’action directe, souvent en marge de la légalité, pour parvenir à leur objectifs, afin de remplacer l’organisation politique actuelle par une autre radicalement différente. Cela peut se faire au travers de la guérilla, ou plus généralement par des méthodes qui sortent du cadre de l’acceptable posé par les institutions politiques…
      help_revo2: Les <b>réformistes</b> auront tendance à privilégier l’action légale pour parvenir à leurs fins, afin de réformer l’organisation politique actuelle petit à petit. Cela peut se faire au travers des institutions, via les élections, les manifestations autorisées, les pétitions…
      
      quiz_loading: Chargement...
      quiz_btn_yes1: Absolument d'accord
      quiz_btn_yes0: Plutôt d'accord
      quiz_btn_neutral: Neutre ou hésitant
      quiz_btn_no0: Plutôt pas d'accord
      quiz_btn_no1: Absolument pas d'accord
      quiz_btn_back_q: Retour à la question précédente
      quiz_btn_back_i: Retour à l'accueil
      quiz_btn_random: Voir un résultat aléatoire
      quiz_question_counter: Question %num% sur %sum%
      
      result_title: Résultats
      result_special: Caractéristiques supplémentaires
      result_desc: Le résultat de votre PolitiScales est décomposé en 8 axes. Chaque axe indique votre positionnement par rapport à deux idéologies contradictoires. Des caractéristiques particulières, affichés en bas de page, peuvent également venir completer votre résultat. Pour plus d'information sur les differents axes, <a href="help.html">consultez la page d'aide</a>."
      result_anarchism: "<b>Anarchisme : </b>quand le peuple est frappé avec un bâton, il n'est pas plus heureux si le bâton est appelé « bâton du peuple ». L'État est une oppression qu'il faut supprimer."
      result_pragmatism: "<b>Pragmatisme : </b>la politique revient à objectivement regarder où sont les problèmes, et chercher à les résoudre en fonction des moyens disponible. La philosophie et les idéologies en générales sont mises de coté au profit de la gestion."
      result_feminism: "<b>Féminisme radical : </b>le genre doit disparaitre pour mettre à mort le patriarcat."
      result_complotism: "<b>Complotisme : </b>les grands problèmes de notre société sont l'oeuvre d'un petit groupe de personnes. Il est donc indispensable de les trouver, d'informer le public de leurs objectifs et de les neutraliser."
      result_veganism: "<b>Véganisme : </b>les humains doivent arrêter à tout prix la consommation et l'exploitation des êtres dit « sensibles »."
      result_monarchism: "<b>Monarchisme : </b>la société devrait être organisée autour d'un roi."
      result_religion: "<b>Missionnaire : </b>pour vous, la religion est importante, surtout la votre. Il convient donc de la diffuser le plus largement possible sur l'ensemble du globe."
      result_btn_redo: Recommencer le test
      
      slogan_constructivism: Égalité
      slogan_internationalism: Humanité
      slogan_nationalism: Patrie
      slogan_communism: Socialisme
      slogan_capitalism: Travail
      slogan_laissez_faire: Liberté
      slogan_conservatism: Famille
      slogan_justice_soft: Justice
      slogan_justice_hard: Ordre
      slogan_ecology: Ecologie
      slogan_revo: Révolution
      
      share_facebook: "Mon résultat sur #PolitiScales : %slogan%"
      share_reddit: "Mon résultat sur #PolitiScales : %slogan%"
      share_twitter: "Mon résultat sur #PolitiScales : %slogan%"
